name: Build, Tag, & Release
on: [push]

jobs:
  Build-Tag-Release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉"

      - uses: actions/checkout@v3

      - name: StreamDeck Distribution Tool
        uses: AdamCarballo/streamdeck-distribution-tool@v1
        with:
          input: com.company.plugin_name.sdPlugin
          output: release
